name: GLaDOS-checkin

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: "5,35 16 * * *"
   #UTC时间比北京时间慢8个小时。上面的时间是每天北京时间零点5分和35分，执行一次任务

jobs:
  GLaDOS-checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: checkin
        env:
          COOKIE: ${{ secrets.COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          ./checkin.sh
